---
# Certificates generation
  - hosts: wazuh_server
    roles:
      - role: ../roles/wazuh/wazuh-indexer
        perform_installation: false
    become: no
    #become_user: root
    vars:
      indexer_node_master: true
      instances:
        node1:
          name: node-1       # Important: must be equal to indexer_node_name.
          ip: 127.0.0.1
          role: indexer
    tags:
      - generate-certs
# Single node
  - hosts: wazuh_server
    become: yes
    become_user: root
    roles:
      - role: ../roles/wazuh/wazuh-indexer
      - role: ../roles/wazuh/ansible-wazuh-manager
      - role: ../roles/wazuh/ansible-filebeat-oss
      - role: ../roles/wazuh/wazuh-dashboard
    vars:
      single_node: true
      minimum_master_nodes: 1
      indexer_node_master: true
      indexer_network_host: 127.0.0.1
      filebeat_node_name: node-1
      filebeat_output_indexer_hosts:
      - 127.0.0.1
      instances:
        node1:
          name: node-1       # Important: must be equal to indexer_node_name.
          ip: 127.0.0.1
          role: indexer
      ansible_shell_allow_world_readable_temp: true
      indexer_admin_password: "{{ vault_indexer_admin_password }}"
      indexer_security_password: "{{ vault_indexer_admin_password }}"
      wazuh_api_credentials:
          - id: default
            url: https://127.0.0.1
            port: 55000
            username: wazuh-wui
            password: "{{ vault_api_password }}"
      wazuh_api_users:
        - username: wazuh-wui
          password: "{{ vault_api_password }}"
      wazuh_manager_integrations:
        - name: custom-soarca
          hook_url: 'http://10.70.4.6:8080'
          alert_format: 'json'
          rule_id: 554
      shared_agent_config:
        - type: os
          type_value: Windows
          syscheck:
            disable: 'no'
            directories:
              - dirs: C:\Users\*\Documents
                checks: 'check_all="yes" realtime="yes"'            
              - dirs: C:\Users\*\Downloads
                checks: 'check_all="yes" realtime="yes"'
            
        

